# Generated by Django 3.1.1 on 2020-09-19 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('best_cricketer', models.CharField(blank=True, max_length=32, null=True)),
                ('white', models.CharField(blank=True, max_length=32, null=True)),
                ('yellow', models.CharField(blank=True, max_length=32, null=True)),
                ('orange', models.CharField(blank=True, max_length=32, null=True)),
                ('green', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
